apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nkhm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0035-tenant/tkwch-fix-0075-0035-app/devfile-sample-nkhm@sha256:84b0c6053ab86a5e3ac6946c9e9bfa6121928c4ecdf63cfed970e10bf7bdf160
        name: my-nodejs
        resources: {}
status: {}
